services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        container_name: 'pullus-service-api-server'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8199}:80'
            - '${VITE_PORT:-5991}:${VITE_PORT:-5190}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: 'pullus-service-api-mysql'
        ports:
            - '${FORWARD_DB_PORT:-3111}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - './docker/db:/var/lib/mysql'
        networks:
            - sail

    phpmyadmin:
        image: 'phpmyadmin:latest'
        container_name: 'pullus-service-api-pmaboon'
        environment:
            PMA_HOST: '${DB_HOST}'
            PMA_PORT: '${DB_PORT}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - '${PMA_PORT:-5105}:80'
        networks:
            - sail
        depends_on:
            - mysql

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
